version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:8.0.0
    volumes:
      - ./grafana:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_password
    ports:
      - '3000:3000'
    networks:
      - monitoring_network

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
    networks:
      - monitoring_network

  node_exporter:
    image: prom/node-exporter:v1.2.2
    ports:
      - '9100:9100'
    networks:
      - monitoring_network

  traefik:
    image: traefik:v2.11
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

networks:
  monitoring_network:
